# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 17:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Only digits allowed in this field!', regex='^\\d+$')])),
                ('address_actual', models.CharField(max_length=200)),
                ('address_registered', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(null=True)),
                ('price_type', models.CharField(choices=[('R', 'Rent'), ('S', 'Sale')], max_length=1)),
                ('established_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('established_date',),
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_rent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('realestate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulator.RealEstate')),
                ('description', models.TextField()),
                ('flat_type', models.CharField(choices=[('R', 'Regular'), ('S', 'Studio')], max_length=1)),
                ('per_room_basis', models.BooleanField(default=False)),
                ('new_build', models.BooleanField(default=False)),
            ],
            bases=('simulator.realestate',),
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('owner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulator.Owner')),
                ('company_name', models.CharField(max_length=100)),
                ('inn', models.CharField(blank=True, default='', max_length=12, validators=[django.core.validators.RegexValidator(message='Only digits allowed in this field!', regex='^\\d+$')])),
            ],
            bases=('simulator.owner',),
        ),
        migrations.CreateModel(
            name='PhysicalEntity',
            fields=[
                ('owner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulator.Owner')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('third_name', models.CharField(blank=True, default='', max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField(null=True)),
                ('passport_series', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Only digits allowed in this field!', regex='^\\d+$')])),
                ('passport_number', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Only digits allowed in this field!', regex='^\\d+$')])),
                ('passport_issued_date', models.DateField(null=True)),
            ],
            bases=('simulator.owner',),
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('deal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulator.Deal')),
                ('from_date', models.DateField()),
                ('till_date', models.DateField()),
            ],
            bases=('simulator.deal',),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('realestate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulator.RealEstate')),
                ('room_type', models.CharField(choices=[('B', 'Bathroom'), ('K', 'Kitchen'), ('L', 'Living Room')], max_length=1)),
                ('square', models.SmallIntegerField()),
                ('parent_flat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simulator.Flat')),
            ],
            bases=('simulator.realestate',),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('deal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulator.Deal')),
                ('deal_date', models.DateField()),
            ],
            bases=('simulator.deal',),
        ),
        migrations.AddField(
            model_name='realestate',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='real_estate_property', to='simulator.Owner'),
        ),
        migrations.AddField(
            model_name='price',
            name='real_estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simulator.RealEstate'),
        ),
        migrations.AddField(
            model_name='deal',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='simulator.Owner'),
        ),
        migrations.AddField(
            model_name='deal',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor', to='simulator.Owner'),
        ),
    ]
