# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 23:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Only digits allowed in this field!', regex='^\\d+$')])),
                ('address_actual', models.CharField(max_length=200)),
                ('address_registered', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('owner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulator.Owner')),
                ('company_name', models.CharField(max_length=100)),
                ('inn', models.CharField(blank=True, default='', max_length=12, validators=[django.core.validators.RegexValidator(message='Only digits allowed in this field!', regex='^\\d+$')])),
            ],
            bases=('simulator.owner',),
        ),
        migrations.CreateModel(
            name='PhysicalEntity',
            fields=[
                ('owner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulator.Owner')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('third_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.CharField(blank=True, default='', max_length=3, validators=[django.core.validators.RegexValidator(message='Only digits allowed in this field!', regex='^\\d+$')])),
                ('passport_series', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Only digits allowed in this field!', regex='^\\d+$')])),
                ('passport_number', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Only digits allowed in this field!', regex='^\\d+$')])),
                ('passport_issued_date', models.DateField()),
            ],
            bases=('simulator.owner',),
        ),
    ]
